FROM debian:bullseye-slim

ENV \
    MAINTAINER="Jardson Viana" \
    EMAIL=jardson.consultoria@gmail.com \
    TERM=xterm \
    TZ=America/Sao_Paulo \
    PS1='\u@\h:\w\$ '

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    apache2 apache2-utils ca-certificates \
    libapache2-mod-php php php-mysql \
    php-cli php-pear php-gmp php-gd \
    php-bcmath php-mbstring php-curl \
    php-xml php-zip \
    nano wget unzip \
    && a2enmod rewrite && a2enmod headers \
    && sed -i 's/ServerTokens OS/ServerTokens Prod/' /etc/apache2/conf-available/security.conf \
    && sed -i 's/ServerSignature On/ServerSignature Off/' /etc/apache2/conf-available/security.conf \
    && echo '<?php phpinfo(); ?>' > /var/www/html/phpinfo.php \
    && rm /etc/localtime \
    && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && mkdir /var/www/wordpress/ \
    && wget https://br.wordpress.org/latest-pt_BR.zip -P /tmp/ \
    && unzip /tmp/latest-pt_BR.zip -d /tmp/ \
    && mv /tmp/wordpress/* /var/www/wordpress/ \
    && chown www-data. /var/www/wordpress/ -R \
    && rm -Rf /tmp/* \
    && apt remove --purge -y wget unzip \
    && apt autoremove \
    && apt clean \
    && rm -rf /var/cache/apt/*

COPY ./apache2/000-default.conf /etc/apache2/sites-enabled/

COPY ./apache2/php.ini /etc/php/7.4/apache2/

EXPOSE 80

CMD ["apachectl", "-D",  "FOREGROUND"]
