FROM debian:bullseye-slim

ENV \
    MAINTAINER="Jardson Viana" \
    EMAIL=jardson.consultoria@gmail.com \
    TERM=xterm \
    TZ=America/Sao_Paulo \
    PS1='\u@\h:\w\$ ' \
    DOMAIN=jvconsultisp.com.br

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    apache2 apache2-utils \
    libapache2-mod-php php php-mysql \
    php-cli php-pear php-gmp php-gd \
    php-bcmath php-mbstring php-curl \
    php-xml php-zip \
    nano wget unzip \
    certbot python3-certbot-apache \
    && a2enmod rewrite && a2enmod headers \
    && wget https://github.com/JardsonViana/zabbix-6-debian11/raw/main/conf-apache2 -O /etc/apache2/sites-enabled/000-default.conf \
    && sed -i 's/ServerTokens OS/ServerTokens Prod/' /etc/apache2/conf-available/security.conf \
    && sed -i 's/ServerSignature On/ServerSignature Off/' /etc/apache2/conf-available/security.conf \
    && echo '<?php phpinfo(); ?>' > /var/www/html/phpinfo.php \
    && rm /etc/localtime \
    && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && touch /etc/apache2/sites-available/wordpress.conf \
    && mkdir /var/www/wordpress/ \
    && mkdir /var/www/wordpress/apache2 \
    && a2ensite wordpress \
    && wget https://br.wordpress.org/latest-pt_BR.zip -P /tmp/ \
    && unzip /tmp/latest-pt_BR.zip -d /tmp/ \
    && mv /tmp/wordpress/* /var/www/wordpress/ \
    && chown www-data. /var/www/wordpress/ -R \
    && mv /etc/apache2/sites-available/wordpress.conf /var/www/wordpress/apache2/ \
    && mv /etc/php/7.4/apache2/php.ini /var/www/wordpress/apache2/ \
    && mv /etc/apache2/ports.conf /var/www/wordpress/apache2/ \
    && ln -s "/var/www/wordpress/apache2/wordpress.conf" "/etc/apache2/sites-available/" \
    && ln -s "/var/www/wordpress/apache2/php.ini" "/etc/php/7.4/apache2/" \
    && ln -s "/var/www/wordpress/apache2/ports.conf" "/etc/apache2/" \
    && rm -Rf /tmp/* \
    && apt remove --purge -y wget unzip \
    && apt autoremove \
    && apt clean \
    && rm -rf /var/cache/apt/*


CMD ["apachectl", "-D",  "FOREGROUND"]
