FROM debian:bullseye-slim

ENV \
    MAINTAINER="Jardson Viana" \
    EMAIL=jardson.consultoria@gmail.com \
    TERM=xterm \
    LANG=pt_BR.UTF-8 \
    LANGUAGE=pt_BR.UTF-8 \
    LC_ALL=pt_BR.UTF-8 \
    TZ=America/Sao_Paulo \
    PS1='\u@\h:\w\$ ' \
    DOMAIN=jvconsultisp.com.br

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt install --no-install-recommends -y locales wget ca-certificates && \
    echo "America/Sao_Paulo" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata && \
    sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="pt_BR.UTF-8"' > /etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=pt_BR.UTF-8 && \
    apt-get install --no-install-recommends -y \
    apache2 apache2-utils \
    libapache2-mod-php php php-mysql \
    php-cli php-pear php-gmp php-gd \
    php-bcmath php-mbstring php-curl \
    php-xml php-zip nano \
    certbot python3-certbot-apache \
    && a2enmod rewrite && a2enmod headers \
    && wget https://github.com/JardsonViana/zabbix-6-debian11/raw/main/conf-apache2 -O /etc/apache2/sites-enabled/000-default.conf \
    && sed -i 's/ServerTokens OS/ServerTokens Prod/' /etc/apache2/conf-available/security.conf \
    && sed -i 's/ServerSignature On/ServerSignature Off/' /etc/apache2/conf-available/security.conf \
    && echo '<?php phpinfo(); ?>' > /var/www/html/phpinfo.php \
    && rm /etc/localtime \
    && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && cd /tmp/ \
    && wget https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-3%2Bdebian11_all.deb \
    && dpkg -i zabbix-release_6.0-3+debian11_all.deb \
    && apt update \
    && apt-get install --no-install-recommends -y zabbix-frontend-php \
    && apt-get install --no-install-recommends -y zabbix-apache-conf \
    && sed -i 's/Europe/America/' /etc/zabbix/apache.conf \
    && sed -i 's/Riga/Sao_Paulo/' /etc/zabbix/apache.conf \
    && sed -i 's/memory_limit 128M/memory_limit 512M/' /etc/zabbix/apache.conf \
    && sed -i 's/post_max_size 16M/post_max_size 48M/' /etc/zabbix/apache.conf \
    && sed -i 's/upload_max_filesize 2M/upload_max_filesize 24M/' /etc/zabbix/apache.conf \
    && sed -i 's/Europe/America/' /etc/zabbix/apache.conf \
    && sed -i 's/Riga/Sao_Paulo/' /etc/zabbix/apache.conf \
    && sed -i 's/# php_value/php_value/' /etc/zabbix/apache.conf \
    && sed -i 's/ServerTokens OS/ServerTokens Prod/' /etc/apache2/conf-available/security.conf \
    && sed -i 's/ServerSignature On/ServerSignature Off/' /etc/apache2/conf-available/security.conf \
    && apt autoremove \
    && apt clean \
    && rm -rf /var/cache/apt/*

EXPOSE 80/TCP 443/TCP

CMD ["apachectl", "-D",  "FOREGROUND"]
