FROM debian:bullseye-slim

ENV \
    MAINTAINER="Jardson Viana" \
    EMAIL=jardson.consultoria@gmail.com \
    TERM=xterm \
    TZ=America/Sao_Paulo \
    PS1='\u@\h:\w\$ ' \
    GLPI_VAR_DIR=/opt/glpi/files \
    GLPI_CONFIG_DIR=/opt/glpi/config


ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    apache2 apache2-utils \
    libapache2-mod-php php php-mysql \
    php-cli php-pear php-gmp php-gd \
    php-bcmath php-mbstring php-curl \
    php-xml php-zip \
    php-imagick php-bz2 php-imap \
    php-memcache php-pspell php-tidy \
    php-xmlrpc php-xsl php-imap php-ldap \
    php-file-iterator php-json \
    php-intl php-cas php-apcu \
    wget curl unzip \
    && a2enmod rewrite && a2enmod headers \
    && sed -i 's/ServerTokens OS/ServerTokens Prod/' /etc/apache2/conf-available/security.conf \
    && sed -i 's/ServerSignature On/ServerSignature Off/' /etc/apache2/conf-available/security.conf \
    && echo '<?php phpinfo(); ?>' > /var/www/html/phpinfo.php \
    && rm /etc/localtime \
    && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && wget --no-check-certificate https://github.com/glpi-project/glpi/releases/download/10.0.5/glpi-10.0.5.tgz -P /var/www/html \
    && cd /var/www/html/ \
    && tar -vxf glpi-10.0.5.tgz \
    && chown www-data. -R /var/www/html/glpi/ \
    && mkdir /opt/glpi \
    && mv /var/www/html/glpi/files /opt/glpi/ \
    && mv /var/www/html/glpi/config /opt/glpi/ \
    && rm -f /var/www/html/*.tgz \
    && apt remove --purge -y wget unzip \
    && apt autoremove \
    && apt clean \
    && rm -rf /var/cache/apt/*

COPY 000-default.conf /etc/apache2/sites-enabled/

COPY php.ini /etc/php/7.4/apache2/

EXPOSE 80/TCP 443/TCP

CMD ["apachectl", "-D",  "FOREGROUND"]
